name: Docker Image CI

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract tag name
        id: tag_name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build and push java image
        run: |
          docker build -t tomologic/java:${{ env.TAG }} .
          docker push tomologic/java:${{ env.TAG }}
      - name: Build and push maven image
        run: |
          cd maven
          docker build \
            --build-arg BASE_IMAGE=tomologic/java:${{ env.TAG }} \
            -t tomologic/java:${{ env.TAG }}-maven .
          docker push tomologic/java:${{ env.TAG }}-maven
